schema_version = "1.0.0"

id = "Individual_Camera_Properties"
version = "0.0.1"
name = "Individual Camera Properties"
tagline = "Scene, Render, Resolution properties for each camera instance"
maintainer = "Alexander Bicukow <bicukow@gmail.com>"

type = "add-on"
tags = ["Camera"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]